<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="7" passed="7">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="141" started-at="2018-06-26T07:27:38Z" finished-at="2018-06-26T07:27:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="141" started-at="2018-06-26T07:27:38Z" finished-at="2018-06-26T07:27:38Z">
      <class name="src.main.test.Board_test">
        <test-method status="PASS" signature="sucessfull_registration()[pri:0, instance:src.main.test.Board_test@18be83e4]" name="sucessfull_registration" duration-ms="62" started-at="2018-06-26T12:57:38Z" finished-at="2018-06-26T12:57:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sucessfull_registration -->
        <test-method status="PASS" signature="unique_name_registration_test()[pri:0, instance:src.main.test.Board_test@18be83e4]" name="unique_name_registration_test" duration-ms="0" started-at="2018-06-26T12:57:38Z" depends-on-methods="src.main.test.Board_test.sucessfull_registration" finished-at="2018-06-26T12:57:38Z">
          <exception class="com.qainfotech.tap.training.snl.api.PlayerExistsException">
            <message>
              <![CDATA[Player 'pradeep kumar' already exists on board]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.PlayerExistsException: Player 'pradeep kumar' already exists on board
	at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:73)
	at src.main.test.Board_test.unique_name_registration_test(Board_test.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.PlayerExistsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- unique_name_registration_test -->
        <test-method status="PASS" signature="check_maximum_player_test()[pri:0, instance:src.main.test.Board_test@18be83e4]" name="check_maximum_player_test" duration-ms="15" started-at="2018-06-26T12:57:38Z" depends-on-methods="src.main.test.Board_test.unique_name_registration_test" finished-at="2018-06-26T12:57:38Z">
          <exception class="com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption">
            <message>
              <![CDATA[The board already has maximum allowed Player: 4]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption: The board already has maximum allowed Player: 4
	at com.qainfotech.tap.training.snl.api.Board.registerPlayer(Board.java:68)
	at src.main.test.Board_test.check_maximum_player_test(Board_test.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.MaxPlayersReachedExeption -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- check_maximum_player_test -->
        <test-method status="PASS" signature="roll_dice_test_for_positive_result()[pri:0, instance:src.main.test.Board_test@18be83e4]" name="roll_dice_test_for_positive_result" duration-ms="0" started-at="2018-06-26T12:57:38Z" depends-on-methods="src.main.test.Board_test.check_maximum_player_test" finished-at="2018-06-26T12:57:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- roll_dice_test_for_positive_result -->
        <test-method status="PASS" signature="roll_dice_test_for_negative_result()[pri:0, instance:src.main.test.Board_test@18be83e4]" name="roll_dice_test_for_negative_result" duration-ms="0" started-at="2018-06-26T12:57:38Z" depends-on-methods="src.main.test.Board_test.roll_dice_test_for_positive_result" finished-at="2018-06-26T12:57:38Z">
          <exception class="com.qainfotech.tap.training.snl.api.InvalidTurnException">
            <message>
              <![CDATA[Player '7bfb5800-d810-41f4-bfd4-b3cdb9145535' does not have the turn]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.InvalidTurnException: Player '7bfb5800-d810-41f4-bfd4-b3cdb9145535' does not have the turn
	at com.qainfotech.tap.training.snl.api.Board.rollDice(Board.java:176)
	at src.main.test.Board_test.roll_dice_test_for_negative_result(Board_test.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.InvalidTurnException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- roll_dice_test_for_negative_result -->
        <test-method status="PASS" signature="testingdatatypeforuuid()[pri:0, instance:src.main.test.Board_test@18be83e4]" name="testingdatatypeforuuid" duration-ms="16" started-at="2018-06-26T12:57:38Z" depends-on-methods="src.main.test.Board_test.do_deletion_after_removal_must_throw_exception" finished-at="2018-06-26T12:57:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testingdatatypeforuuid -->
        <test-method status="PASS" signature="do_deletion_after_removal_must_throw_exception()[pri:0, instance:src.main.test.Board_test@18be83e4]" name="do_deletion_after_removal_must_throw_exception" duration-ms="0" started-at="2018-06-26T12:57:38Z" depends-on-methods="src.main.test.Board_test.roll_dice_test_for_negative_result" finished-at="2018-06-26T12:57:38Z">
          <exception class="com.qainfotech.tap.training.snl.api.NoUserWithSuchUUIDException">
            <message>
              <![CDATA[No Player with uuid '7bfb5800-d810-41f4-bfd4-b3cdb9145535' on board]]>
            </message>
            <full-stacktrace>
              <![CDATA[com.qainfotech.tap.training.snl.api.NoUserWithSuchUUIDException: No Player with uuid '7bfb5800-d810-41f4-bfd4-b3cdb9145535' on board
	at com.qainfotech.tap.training.snl.api.Board.deletePlayer(Board.java:122)
	at src.main.test.Board_test.do_deletion_after_removal_must_throw_exception(Board_test.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- com.qainfotech.tap.training.snl.api.NoUserWithSuchUUIDException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- do_deletion_after_removal_must_throw_exception -->
      </class> <!-- src.main.test.Board_test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
